/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarrierSignup = IDL.Record({
  'workEmail' : IDL.Text,
  'mcOrUsdotNumber' : IDL.Text,
  'companyName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'hiringNeeds' : IDL.Text,
  'fleetSize' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCarrierSignups' : IDL.Func([], [IDL.Vec(CarrierSignup)], ['query']),
  'submitCarrierSignup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarrierSignup = IDL.Record({
    'workEmail' : IDL.Text,
    'mcOrUsdotNumber' : IDL.Text,
    'companyName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'hiringNeeds' : IDL.Text,
    'fleetSize' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCarrierSignups' : IDL.Func([], [IDL.Vec(CarrierSignup)], ['query']),
    'submitCarrierSignup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };